# Generated by Django 5.1.2 on 2024-10-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_active_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
