# Generated by Django 5.1.2 on 2024-10-31 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_last_active_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_active_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
