# Generated by Django 5.1.2 on 2024-11-07 12:06

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ადგილი"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="აღწერა"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="products/", verbose_name="ფოტო"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="მინიმუმი წონა",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="სახელი"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="ფასი"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="eshop.tag",
                verbose_name="ტეგები",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="წონა",
            ),
        ),
    ]
