# Generated by Django 5.1.2 on 2024-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0002_alter_product_country_of_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="აღწერა"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ka",
            field=models.TextField(blank=True, null=True, verbose_name="აღწერა"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="სახელი"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ka",
            field=models.CharField(max_length=255, null=True, verbose_name="სახელი"),
        ),
    ]
