# Generated by Django 5.1.2 on 2024-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0003_product_description_en_product_description_ka_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="country_of_origin_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ადგილი"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country_of_origin_ka",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ადგილი"
            ),
        ),
    ]
