# Generated by Django 5.1.2 on 2024-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0004_product_country_of_origin_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_weight_en",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="მინიმუმი წონა",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="min_weight_ka",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="მინიმუმი წონა",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_en",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="ფასი"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_ka",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="ფასი"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quality_en",
            field=models.CharField(
                choices=[("Organic", "Organic"), ("Non-Organic", "Non-Organic")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quality_ka",
            field=models.CharField(
                choices=[("Organic", "Organic"), ("Non-Organic", "Non-Organic")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_en",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="წონა",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_ka",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="წონა",
            ),
        ),
    ]
