# Generated by Django 5.1.2 on 2024-10-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0004_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="eshop.tag"
            ),
        ),
    ]
