# Generated by Django 5.1.2 on 2024-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0005_product_min_weight_en_product_min_weight_ka_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="სახელი"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ka",
            field=models.CharField(max_length=200, null=True, verbose_name="სახელი"),
        ),
    ]
