# Generated by Django 5.1.2 on 2024-10-24 13:50

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0005_tag_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_poi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5", editable=False, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="products/"
            ),
        ),
    ]
