# Generated by Django 5.1.2 on 2024-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0007_remove_category_name_en_remove_category_name_ka"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="სახელი"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ka",
            field=models.CharField(max_length=200, null=True, verbose_name="სახელი"),
        ),
    ]
