# Generated by Django 5.1.2 on 2024-11-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0008_category_name_en_category_name_ka"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="min_weight_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_weight_ka",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_ka",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_ka",
        ),
    ]
